// Code generated by protoc-gen-go. DO NOT EDIT.
// source: teacher.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Teacher struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Department           string   `protobuf:"bytes,4,opt,name=Department,proto3" json:"Department,omitempty"`
	IsHead               bool     `protobuf:"varint,5,opt,name=IsHead,proto3" json:"IsHead,omitempty"`
	SchoolCode           int64    `protobuf:"varint,6,opt,name=SchoolCode,proto3" json:"SchoolCode,omitempty"`
	IdentityNumber       int64    `protobuf:"varint,7,opt,name=IdentityNumber,proto3" json:"IdentityNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Teacher) Reset()         { *m = Teacher{} }
func (m *Teacher) String() string { return proto.CompactTextString(m) }
func (*Teacher) ProtoMessage()    {}
func (*Teacher) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4d93a072aeccf3, []int{0}
}

func (m *Teacher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Teacher.Unmarshal(m, b)
}
func (m *Teacher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Teacher.Marshal(b, m, deterministic)
}
func (m *Teacher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Teacher.Merge(m, src)
}
func (m *Teacher) XXX_Size() int {
	return xxx_messageInfo_Teacher.Size(m)
}
func (m *Teacher) XXX_DiscardUnknown() {
	xxx_messageInfo_Teacher.DiscardUnknown(m)
}

var xxx_messageInfo_Teacher proto.InternalMessageInfo

func (m *Teacher) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Teacher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Teacher) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Teacher) GetDepartment() string {
	if m != nil {
		return m.Department
	}
	return ""
}

func (m *Teacher) GetIsHead() bool {
	if m != nil {
		return m.IsHead
	}
	return false
}

func (m *Teacher) GetSchoolCode() int64 {
	if m != nil {
		return m.SchoolCode
	}
	return 0
}

func (m *Teacher) GetIdentityNumber() int64 {
	if m != nil {
		return m.IdentityNumber
	}
	return 0
}

type AddTeacherRequest struct {
	Input                *Teacher `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTeacherRequest) Reset()         { *m = AddTeacherRequest{} }
func (m *AddTeacherRequest) String() string { return proto.CompactTextString(m) }
func (*AddTeacherRequest) ProtoMessage()    {}
func (*AddTeacherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4d93a072aeccf3, []int{1}
}

func (m *AddTeacherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTeacherRequest.Unmarshal(m, b)
}
func (m *AddTeacherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTeacherRequest.Marshal(b, m, deterministic)
}
func (m *AddTeacherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTeacherRequest.Merge(m, src)
}
func (m *AddTeacherRequest) XXX_Size() int {
	return xxx_messageInfo_AddTeacherRequest.Size(m)
}
func (m *AddTeacherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTeacherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTeacherRequest proto.InternalMessageInfo

func (m *AddTeacherRequest) GetInput() *Teacher {
	if m != nil {
		return m.Input
	}
	return nil
}

type GetTeacherRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTeacherRequest) Reset()         { *m = GetTeacherRequest{} }
func (m *GetTeacherRequest) String() string { return proto.CompactTextString(m) }
func (*GetTeacherRequest) ProtoMessage()    {}
func (*GetTeacherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4d93a072aeccf3, []int{2}
}

func (m *GetTeacherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeacherRequest.Unmarshal(m, b)
}
func (m *GetTeacherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeacherRequest.Marshal(b, m, deterministic)
}
func (m *GetTeacherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeacherRequest.Merge(m, src)
}
func (m *GetTeacherRequest) XXX_Size() int {
	return xxx_messageInfo_GetTeacherRequest.Size(m)
}
func (m *GetTeacherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeacherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeacherRequest proto.InternalMessageInfo

func (m *GetTeacherRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteTeacherRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTeacherRequest) Reset()         { *m = DeleteTeacherRequest{} }
func (m *DeleteTeacherRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTeacherRequest) ProtoMessage()    {}
func (*DeleteTeacherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4d93a072aeccf3, []int{3}
}

func (m *DeleteTeacherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeacherRequest.Unmarshal(m, b)
}
func (m *DeleteTeacherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeacherRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTeacherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeacherRequest.Merge(m, src)
}
func (m *DeleteTeacherRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTeacherRequest.Size(m)
}
func (m *DeleteTeacherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeacherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeacherRequest proto.InternalMessageInfo

func (m *DeleteTeacherRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type UpdateTeacherRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Input                *Teacher `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTeacherRequest) Reset()         { *m = UpdateTeacherRequest{} }
func (m *UpdateTeacherRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTeacherRequest) ProtoMessage()    {}
func (*UpdateTeacherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4d93a072aeccf3, []int{4}
}

func (m *UpdateTeacherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeacherRequest.Unmarshal(m, b)
}
func (m *UpdateTeacherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeacherRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTeacherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeacherRequest.Merge(m, src)
}
func (m *UpdateTeacherRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTeacherRequest.Size(m)
}
func (m *UpdateTeacherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeacherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeacherRequest proto.InternalMessageInfo

func (m *UpdateTeacherRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateTeacherRequest) GetInput() *Teacher {
	if m != nil {
		return m.Input
	}
	return nil
}

type AddTeacherResponse struct {
	Teacher              *Teacher `protobuf:"bytes,1,opt,name=teacher,proto3" json:"teacher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTeacherResponse) Reset()         { *m = AddTeacherResponse{} }
func (m *AddTeacherResponse) String() string { return proto.CompactTextString(m) }
func (*AddTeacherResponse) ProtoMessage()    {}
func (*AddTeacherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4d93a072aeccf3, []int{5}
}

func (m *AddTeacherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTeacherResponse.Unmarshal(m, b)
}
func (m *AddTeacherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTeacherResponse.Marshal(b, m, deterministic)
}
func (m *AddTeacherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTeacherResponse.Merge(m, src)
}
func (m *AddTeacherResponse) XXX_Size() int {
	return xxx_messageInfo_AddTeacherResponse.Size(m)
}
func (m *AddTeacherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTeacherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTeacherResponse proto.InternalMessageInfo

func (m *AddTeacherResponse) GetTeacher() *Teacher {
	if m != nil {
		return m.Teacher
	}
	return nil
}

type GetTeachersRequest struct {
	SchoolCode           int64    `protobuf:"varint,1,opt,name=SchoolCode,proto3" json:"SchoolCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTeachersRequest) Reset()         { *m = GetTeachersRequest{} }
func (m *GetTeachersRequest) String() string { return proto.CompactTextString(m) }
func (*GetTeachersRequest) ProtoMessage()    {}
func (*GetTeachersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4d93a072aeccf3, []int{6}
}

func (m *GetTeachersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeachersRequest.Unmarshal(m, b)
}
func (m *GetTeachersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeachersRequest.Marshal(b, m, deterministic)
}
func (m *GetTeachersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeachersRequest.Merge(m, src)
}
func (m *GetTeachersRequest) XXX_Size() int {
	return xxx_messageInfo_GetTeachersRequest.Size(m)
}
func (m *GetTeachersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeachersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeachersRequest proto.InternalMessageInfo

func (m *GetTeachersRequest) GetSchoolCode() int64 {
	if m != nil {
		return m.SchoolCode
	}
	return 0
}

type GetTeachersResponse struct {
	Teacher              []*Teacher `protobuf:"bytes,1,rep,name=teacher,proto3" json:"teacher,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetTeachersResponse) Reset()         { *m = GetTeachersResponse{} }
func (m *GetTeachersResponse) String() string { return proto.CompactTextString(m) }
func (*GetTeachersResponse) ProtoMessage()    {}
func (*GetTeachersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c4d93a072aeccf3, []int{7}
}

func (m *GetTeachersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeachersResponse.Unmarshal(m, b)
}
func (m *GetTeachersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeachersResponse.Marshal(b, m, deterministic)
}
func (m *GetTeachersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeachersResponse.Merge(m, src)
}
func (m *GetTeachersResponse) XXX_Size() int {
	return xxx_messageInfo_GetTeachersResponse.Size(m)
}
func (m *GetTeachersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeachersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeachersResponse proto.InternalMessageInfo

func (m *GetTeachersResponse) GetTeacher() []*Teacher {
	if m != nil {
		return m.Teacher
	}
	return nil
}

func init() {
	proto.RegisterType((*Teacher)(nil), "pb.Teacher")
	proto.RegisterType((*AddTeacherRequest)(nil), "pb.AddTeacherRequest")
	proto.RegisterType((*GetTeacherRequest)(nil), "pb.GetTeacherRequest")
	proto.RegisterType((*DeleteTeacherRequest)(nil), "pb.DeleteTeacherRequest")
	proto.RegisterType((*UpdateTeacherRequest)(nil), "pb.UpdateTeacherRequest")
	proto.RegisterType((*AddTeacherResponse)(nil), "pb.AddTeacherResponse")
	proto.RegisterType((*GetTeachersRequest)(nil), "pb.GetTeachersRequest")
	proto.RegisterType((*GetTeachersResponse)(nil), "pb.GetTeachersResponse")
}

func init() {
	proto.RegisterFile("teacher.proto", fileDescriptor_6c4d93a072aeccf3)
}

var fileDescriptor_6c4d93a072aeccf3 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x4e, 0xf2, 0x50,
	0x10, 0xfd, 0xda, 0xf2, 0xf3, 0x39, 0x04, 0x22, 0x23, 0xe2, 0x0d, 0x0b, 0x83, 0x35, 0x12, 0x56,
	0x2c, 0xd0, 0xb8, 0x51, 0x13, 0x09, 0x4d, 0xb4, 0x1b, 0x16, 0x45, 0x1f, 0xa0, 0xa5, 0x13, 0x21,
	0x81, 0xb6, 0xb6, 0x17, 0x13, 0x9f, 0xce, 0xf7, 0xf0, 0x69, 0x4c, 0x6f, 0xdb, 0xf4, 0x87, 0x02,
	0xbb, 0xdb, 0x73, 0xcf, 0x99, 0x99, 0x33, 0xa7, 0x17, 0x9a, 0x9c, 0xcc, 0xc5, 0x92, 0xfc, 0x91,
	0xe7, 0xbb, 0xdc, 0x45, 0xd9, 0xb3, 0xd4, 0x1f, 0x09, 0xea, 0x6f, 0x11, 0x8a, 0x2d, 0x90, 0x75,
	0x8d, 0x49, 0x7d, 0x69, 0xa8, 0x18, 0xb2, 0xae, 0x21, 0x42, 0x65, 0x66, 0x6e, 0x88, 0xc9, 0x7d,
	0x69, 0x78, 0x62, 0x88, 0x33, 0x9e, 0x82, 0x32, 0xf9, 0x20, 0xa6, 0x08, 0x52, 0x78, 0xc4, 0x4b,
	0x00, 0x8d, 0x3c, 0xd3, 0xe7, 0x1b, 0x72, 0x38, 0xab, 0x08, 0x6e, 0x06, 0xc1, 0x2e, 0xd4, 0xf4,
	0xe0, 0x95, 0x4c, 0x9b, 0x55, 0xfb, 0xd2, 0xf0, 0xbf, 0x11, 0x7f, 0x85, 0xba, 0xf9, 0x62, 0xe9,
	0xba, 0xeb, 0xa9, 0x6b, 0x13, 0xab, 0x89, 0x82, 0x19, 0x04, 0x07, 0xd0, 0xd2, 0x6d, 0x72, 0xf8,
	0x8a, 0x7f, 0xcf, 0xb6, 0x1b, 0x8b, 0x7c, 0x56, 0x17, 0x9c, 0x02, 0xaa, 0xde, 0x43, 0x7b, 0x62,
	0xdb, 0xb1, 0x07, 0x83, 0x3e, 0xb7, 0x14, 0x70, 0xbc, 0x82, 0xea, 0xca, 0xf1, 0xb6, 0x5c, 0xb8,
	0x69, 0x8c, 0x1b, 0x23, 0xcf, 0x1a, 0x25, 0x94, 0xe8, 0x46, 0xbd, 0x86, 0xf6, 0x0b, 0xf1, 0x82,
	0xae, 0xb0, 0x02, 0x75, 0x00, 0x1d, 0x8d, 0xd6, 0xc4, 0xe9, 0x08, 0x4f, 0x87, 0xce, 0xbb, 0x67,
	0x9b, 0xc7, 0x78, 0xe9, 0x5c, 0xf2, 0xde, 0xb9, 0x1e, 0x00, 0xb3, 0x7e, 0x02, 0xcf, 0x75, 0x02,
	0xc2, 0x1b, 0xa8, 0xc7, 0xe1, 0x95, 0x59, 0x4a, 0xee, 0xd4, 0x3b, 0xc0, 0xd4, 0x54, 0x90, 0x4c,
	0x91, 0x5f, 0xb5, 0x54, 0x5c, 0xb5, 0xfa, 0x08, 0x67, 0x39, 0x55, 0x59, 0x4f, 0x65, 0x5f, 0xcf,
	0xf1, 0xaf, 0x0c, 0xad, 0x18, 0x9c, 0x93, 0xff, 0xb5, 0x5a, 0x10, 0x3e, 0x01, 0xa4, 0x1e, 0xf0,
	0x3c, 0x94, 0xed, 0x64, 0xd4, 0xeb, 0x16, 0xe1, 0xa8, 0xad, 0xfa, 0x2f, 0x94, 0xa7, 0xf3, 0x44,
	0xf2, 0x9d, 0xa8, 0x0e, 0xc8, 0xa7, 0xd0, 0xcc, 0x85, 0x81, 0x2c, 0xa4, 0x96, 0xe5, 0x73, 0xb8,
	0x48, 0x2e, 0xf9, 0xa8, 0x48, 0xd9, 0xcf, 0x70, 0xa0, 0xc8, 0x33, 0x34, 0x32, 0x8b, 0xc5, 0x6e,
	0xde, 0x49, 0x92, 0x4f, 0xef, 0x62, 0x07, 0x4f, 0x2a, 0x58, 0x35, 0xf1, 0x54, 0x6f, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x34, 0xfa, 0x4e, 0x97, 0xbb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TeacherServiceClient is the client API for TeacherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeacherServiceClient interface {
	AddTeacher(ctx context.Context, in *AddTeacherRequest, opts ...grpc.CallOption) (*AddTeacherResponse, error)
	GetTeacher(ctx context.Context, in *GetTeacherRequest, opts ...grpc.CallOption) (*AddTeacherResponse, error)
	UpdateTeacher(ctx context.Context, in *UpdateTeacherRequest, opts ...grpc.CallOption) (*AddTeacherResponse, error)
	DeleteTeacher(ctx context.Context, in *DeleteTeacherRequest, opts ...grpc.CallOption) (*AddTeacherResponse, error)
	GetTeachers(ctx context.Context, in *GetTeachersRequest, opts ...grpc.CallOption) (*GetTeachersResponse, error)
}

type teacherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTeacherServiceClient(cc grpc.ClientConnInterface) TeacherServiceClient {
	return &teacherServiceClient{cc}
}

func (c *teacherServiceClient) AddTeacher(ctx context.Context, in *AddTeacherRequest, opts ...grpc.CallOption) (*AddTeacherResponse, error) {
	out := new(AddTeacherResponse)
	err := c.cc.Invoke(ctx, "/pb.TeacherService/AddTeacher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) GetTeacher(ctx context.Context, in *GetTeacherRequest, opts ...grpc.CallOption) (*AddTeacherResponse, error) {
	out := new(AddTeacherResponse)
	err := c.cc.Invoke(ctx, "/pb.TeacherService/GetTeacher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) UpdateTeacher(ctx context.Context, in *UpdateTeacherRequest, opts ...grpc.CallOption) (*AddTeacherResponse, error) {
	out := new(AddTeacherResponse)
	err := c.cc.Invoke(ctx, "/pb.TeacherService/UpdateTeacher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) DeleteTeacher(ctx context.Context, in *DeleteTeacherRequest, opts ...grpc.CallOption) (*AddTeacherResponse, error) {
	out := new(AddTeacherResponse)
	err := c.cc.Invoke(ctx, "/pb.TeacherService/DeleteTeacher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) GetTeachers(ctx context.Context, in *GetTeachersRequest, opts ...grpc.CallOption) (*GetTeachersResponse, error) {
	out := new(GetTeachersResponse)
	err := c.cc.Invoke(ctx, "/pb.TeacherService/GetTeachers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeacherServiceServer is the server API for TeacherService service.
type TeacherServiceServer interface {
	AddTeacher(context.Context, *AddTeacherRequest) (*AddTeacherResponse, error)
	GetTeacher(context.Context, *GetTeacherRequest) (*AddTeacherResponse, error)
	UpdateTeacher(context.Context, *UpdateTeacherRequest) (*AddTeacherResponse, error)
	DeleteTeacher(context.Context, *DeleteTeacherRequest) (*AddTeacherResponse, error)
	GetTeachers(context.Context, *GetTeachersRequest) (*GetTeachersResponse, error)
}

// UnimplementedTeacherServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTeacherServiceServer struct {
}

func (*UnimplementedTeacherServiceServer) AddTeacher(ctx context.Context, req *AddTeacherRequest) (*AddTeacherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTeacher not implemented")
}
func (*UnimplementedTeacherServiceServer) GetTeacher(ctx context.Context, req *GetTeacherRequest) (*AddTeacherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeacher not implemented")
}
func (*UnimplementedTeacherServiceServer) UpdateTeacher(ctx context.Context, req *UpdateTeacherRequest) (*AddTeacherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeacher not implemented")
}
func (*UnimplementedTeacherServiceServer) DeleteTeacher(ctx context.Context, req *DeleteTeacherRequest) (*AddTeacherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeacher not implemented")
}
func (*UnimplementedTeacherServiceServer) GetTeachers(ctx context.Context, req *GetTeachersRequest) (*GetTeachersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeachers not implemented")
}

func RegisterTeacherServiceServer(s *grpc.Server, srv TeacherServiceServer) {
	s.RegisterService(&_TeacherService_serviceDesc, srv)
}

func _TeacherService_AddTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).AddTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TeacherService/AddTeacher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).AddTeacher(ctx, req.(*AddTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_GetTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).GetTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TeacherService/GetTeacher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).GetTeacher(ctx, req.(*GetTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_UpdateTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).UpdateTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TeacherService/UpdateTeacher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).UpdateTeacher(ctx, req.(*UpdateTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_DeleteTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).DeleteTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TeacherService/DeleteTeacher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).DeleteTeacher(ctx, req.(*DeleteTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_GetTeachers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeachersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).GetTeachers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TeacherService/GetTeachers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).GetTeachers(ctx, req.(*GetTeachersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TeacherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TeacherService",
	HandlerType: (*TeacherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTeacher",
			Handler:    _TeacherService_AddTeacher_Handler,
		},
		{
			MethodName: "GetTeacher",
			Handler:    _TeacherService_GetTeacher_Handler,
		},
		{
			MethodName: "UpdateTeacher",
			Handler:    _TeacherService_UpdateTeacher_Handler,
		},
		{
			MethodName: "DeleteTeacher",
			Handler:    _TeacherService_DeleteTeacher_Handler,
		},
		{
			MethodName: "GetTeachers",
			Handler:    _TeacherService_GetTeachers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teacher.proto",
}
